# Generated by Django 5.1.4 on 2024-12-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloRedNeuronal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_entrenamiento', models.DateField()),
                ('accuracy', models.FloatField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_redes', to='gestion_proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Modelo de Red Neuronal',
                'verbose_name_plural': 'Modelos de Redes Neuronales',
                'db_table': 'modelo_red_neuronal',
                'ordering': ['id'],
            },
        ),
    ]
