# Generated by Django 5.1.4 on 2024-12-31 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('redes_neuronales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloredneuronal',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_redes', to='dashboard.proyecto'),
        ),
    ]
