version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - python-deps:/app/venv  # Volumen para dependencias Python
    environment:
      - DEBUG=1
      - DB_NAME=Db-Web-App-PM
      - DB_USER=development
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=webapp.settings.development
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Db-Web-App-PM
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  python-deps: