# Generated by Django 5.1.4 on 2024-12-31 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_proyectos', '0001_initial'),
        ('gestion_tareas', '0003_alter_tarea_requerimiento'),
        ('redes_neuronales', '0002_alter_modeloredneuronal_proyecto'),
        ('reporte', '0003_alter_reporte_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requerimiento',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='Requerimiento',
        ),
    ]
