# Generated by Django 5.1.4 on 2024-12-22 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_equipos', '0002_remove_equipo_fecha_creacion_remove_equipo_id_and_more'),
        ('gestion_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='requerimiento',
            options={'verbose_name': 'Requerimiento', 'verbose_name_plural': 'Requerimientos'},
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_fin',
            new_name='fechafin',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechacreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechamodificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='idequipo',
            field=models.ForeignKey(db_column='idequipo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_equipos.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='idproyecto',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombreproyecto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='fechacreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='fechamodificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='idproyecto',
            field=models.ForeignKey(db_column='idproyecto', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_proyectos.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='idrequerimiento',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
