# Generated by Django 5.1.4 on 2024-12-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_equipos', '0001_initial'),
        ('gestion_recursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='gestion_recursos.recurso'),
        ),
    ]
