# Generated by Django 5.1.4 on 2024-12-22 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_equipos', '0001_initial'),
        ('gestion_recursos', '0002_remove_recurso_cantidad_remove_recurso_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fechacreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fechamodificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='idequipo',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombreequipo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('idmiembro', models.AutoField(primary_key=True, serialize=False)),
                ('idequipo', models.ForeignKey(db_column='idequipo', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_equipos.equipo')),
                ('idrecurso', models.ForeignKey(db_column='idrecurso', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_recursos.recurso')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'miembro',
            },
        ),
        migrations.DeleteModel(
            name='MiembroEquipo',
        ),
    ]
