# Generated by Django 5.1.4 on 2024-12-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaLectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'db_table': 'historial_notificacion',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fechaCreacion'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAlerta', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='gestion_tareas.tarea')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
                'ordering': ['-fechaCreacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaResolucion', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='notificaciones.alerta')),
            ],
            options={
                'verbose_name': 'Historial de Alerta',
                'verbose_name_plural': 'Historial de Alertas',
                'db_table': 'historial_alerta',
            },
        ),
    ]
