services:
  db:
    image: postgres:14-alpine
    container_name: dev-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - dev-network
      
  redis:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - dev-network
    # Opcional: para persistencia de datos
    # volumes:
    #   - redis_data:/data

volumes:
  postgres_data:
  pgadmin_data:
  # Si decides usar persistencia para Redis, descomenta la siguiente línea
  # redis_data:

networks:
  dev-network:
    driver: bridge