services:
  web:
    build: .
    container_name: django-web-app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DB_NAME=Db-Web-App-PM
      - DB_USER=development
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=5432
      # Email configuration
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=tu_correo@gmail.com
      - EMAIL_HOST_PASSWORD=tu_password_de_aplicacion
      - EMAIL_USE_TLS=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    container_name: db-web-app
    environment:
      - POSTGRES_DB=Db-Web-App-PM
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U development -d Db-Web-App-PM"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
    name: webapp-pm-postgres-data

networks:
  app-network:
    driver: bridge