# Generated by Django 5.1.4 on 2024-12-22 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_proyectos', '0002_alter_proyecto_options_alter_requerimiento_options_and_more'),
        ('gestion_recursos', '0002_remove_recurso_cantidad_remove_recurso_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idtarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombretarea', models.CharField(max_length=255)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('duracionestimada', models.IntegerField(blank=True, null=True)),
                ('duracionactual', models.IntegerField(blank=True, null=True)),
                ('dificultad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('prioridad', models.IntegerField(blank=True, null=True)),
                ('costoestimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('costoactual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('idrequerimiento', models.ForeignKey(db_column='idrequerimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_proyectos.requerimiento')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tarea',
            },
        ),
        migrations.CreateModel(
            name='Monitoreotarea',
            fields=[
                ('idtarea', models.OneToOneField(db_column='idtarea', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestion_tareas.tarea')),
                ('fechainicioreal', models.DateField(blank=True, null=True)),
                ('fechafinreal', models.DateField(blank=True, null=True)),
                ('porcentajecompletado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alertagenerada', models.BooleanField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Monitoreo Tarea',
                'verbose_name_plural': 'Monitoreo Tareas',
                'db_table': 'monitoreo_tarea',
            },
        ),
        migrations.CreateModel(
            name='Tarearecurso',
            fields=[
                ('idtarea', models.ForeignKey(db_column='idtarea', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestion_tareas.tarea')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('idrecurso', models.ForeignKey(db_column='idrecurso', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_recursos.recurso')),
            ],
            options={
                'verbose_name': 'Tarea Recurso',
                'verbose_name_plural': 'Tareas Recursos',
                'db_table': 'tarea_recurso',
                'unique_together': {('idtarea', 'idrecurso')},
            },
        ),
    ]
