# Generated by Django 5.1.4 on 2024-12-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_proyectos', '0001_initial'),
        ('gestion_recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTarea', models.CharField(max_length=255)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('duracionEstimada', models.PositiveIntegerField(blank=True, null=True)),
                ('duracionActual', models.PositiveIntegerField(blank=True, null=True)),
                ('dificultad', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('prioridad', models.PositiveIntegerField(blank=True, null=True)),
                ('costoEstimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('costoActual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestion_proyectos.requerimiento')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tarea',
            },
        ),
        migrations.CreateModel(
            name='MonitoreoTarea',
            fields=[
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='monitoreo', serialize=False, to='gestion_tareas.tarea')),
                ('fechaInicioReal', models.DateField(blank=True, null=True)),
                ('fechaFinReal', models.DateField(blank=True, null=True)),
                ('porcentajeCompletado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alertaGenerada', models.BooleanField(default=False)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitoreo Tarea',
                'verbose_name_plural': 'Monitoreo Tareas',
                'db_table': 'monitoreo_tarea',
            },
        ),
        migrations.CreateModel(
            name='HistorialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCambio', models.DateTimeField(auto_now_add=True)),
                ('descripcionCambio', models.TextField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion_tareas.tarea')),
            ],
            options={
                'verbose_name': 'Historial de Tarea',
                'verbose_name_plural': 'Historial de Tareas',
                'db_table': 'historial_tarea',
            },
        ),
        migrations.CreateModel(
            name='TareaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_recursos', to='gestion_recursos.recurso')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_recursos', to='gestion_tareas.tarea')),
            ],
            options={
                'verbose_name': 'Tarea Recurso',
                'verbose_name_plural': 'Tareas Recursos',
                'db_table': 'tarea_recurso',
                'unique_together': {('tarea', 'recurso')},
            },
        ),
    ]
