# Generated by Django 5.1.4 on 2024-12-23 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tarea_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='gestion_tareas.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.PositiveIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2),
        ),
    ]
