# Generated by Django 5.1.4 on 2024-12-31 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('gestion_tareas', '0002_tarea_tarea_padre_alter_tarea_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='dashboard.requerimiento'),
        ),
    ]
