# Generated by Django 5.1.4 on 2024-12-22 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='gestion_proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_recurso', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Recursos',
                'db_table': 'tipo_recurso',
            },
        ),
        migrations.CreateModel(
            name='RecursoMaterial',
            fields=[
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion_recursos.recurso')),
                ('costo_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateField()),
            ],
            options={
                'verbose_name': 'Recurso Material',
                'verbose_name_plural': 'Recursos Materiales',
                'db_table': 'recurso_material',
            },
        ),
        migrations.CreateModel(
            name='RecursoHumano',
            fields=[
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion_recursos.recurso')),
                ('cargo', models.CharField(max_length=255)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso Humano',
                'verbose_name_plural': 'Recursos Humanos',
                'db_table': 'recurso_humano',
            },
        ),
    ]
