# Generated by Django 5.1.4 on 2024-12-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idRecurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRecurso', models.CharField(max_length=255)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recurso',
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('idTipoRecurso', models.AutoField(primary_key=True, serialize=False)),
                ('nameTipoRecurso', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Recursos',
                'db_table': 'tipo_recurso',
            },
        ),
        migrations.CreateModel(
            name='RecursoHumano',
            fields=[
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recurso_humano', serialize=False, to='gestion_recursos.recurso')),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('tarifaHora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Recurso Humano',
                'verbose_name_plural': 'Recursos Humanos',
                'db_table': 'recurso_humano',
            },
        ),
        migrations.CreateModel(
            name='RecursoMaterial',
            fields=[
                ('recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recurso_material', serialize=False, to='gestion_recursos.recurso')),
                ('costoUnidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechaCompra', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recurso Material',
                'verbose_name_plural': 'Recursos Materiales',
                'db_table': 'recurso_material',
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='idTipoRecurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='gestion_recursos.tiporecurso'),
        ),
    ]
