# Generated by Django 5.1.4 on 2024-12-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='recurso',
            name='disponibilidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fechacreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fechamodificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='idrecurso',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurso',
            name='idtiporecurso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurso',
            name='nombrerecurso',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
