# Generated by Django 5.1.4 on 2024-12-31 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idactividad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('accion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idalerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipoalerta', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField()),
                ('activa', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entradamodeloestimacionrnn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionentrada', models.TextField(blank=True, null=True)),
                ('tipodato', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'entradamodeloestimacionrnn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreequipo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialalerta',
            fields=[
                ('idhistorial', models.AutoField(primary_key=True, serialize=False)),
                ('fecharesolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historialalerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialnotificacion',
            fields=[
                ('idhistorial', models.AutoField(primary_key=True, serialize=False)),
                ('fechalectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historialnotificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialreporte',
            fields=[
                ('idhistorialreporte', models.AutoField(primary_key=True, serialize=False)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('descripcioncambio', models.TextField()),
            ],
            options={
                'db_table': 'historialreporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialreporteusuario',
            fields=[
                ('idhistorialreporteusuario', models.AutoField(primary_key=True, serialize=False)),
                ('cambio', models.TextField()),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historialreporteusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialtarea',
            fields=[
                ('idhistorialtarea', models.AutoField(primary_key=True, serialize=False)),
                ('fechacambio', models.DateTimeField(blank=True, null=True)),
                ('descripcioncambio', models.TextField()),
            ],
            options={
                'db_table': 'historialtarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('idmiembro', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'miembro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modeloestimacionrnn',
            fields=[
                ('idmodelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombremodelo', models.CharField(max_length=255)),
                ('descripcionmodelo', models.TextField(blank=True, null=True)),
                ('versionmodelo', models.CharField(blank=True, max_length=50, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modeloestimacionrnn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idtarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombretarea', models.CharField(max_length=255)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('duracionestimada', models.IntegerField(blank=True, null=True)),
                ('duracionactual', models.IntegerField(blank=True, null=True)),
                ('dificultad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('prioridad', models.IntegerField(blank=True, null=True)),
                ('costoestimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('costoactual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idnotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('idproyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproyecto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('presupuestoutilizado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idrecurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(max_length=255)),
                ('idtiporecurso', models.IntegerField()),
                ('disponibilidad', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('idreporte', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeporte', models.CharField(max_length=50)),
                ('fechageneracion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporteusuario',
            fields=[
                ('idreporteusuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reporteusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('idrequerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requerimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rolmoduloacceso',
            fields=[
                ('idrolmodulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=255)),
                ('permisos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rolmoduloacceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salidamodeloestimacionrnn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metricasalida', models.TextField(blank=True, null=True)),
                ('tipodato', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'salidamodeloestimacionrnn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiporecurso',
            fields=[
                ('idtiporecurso', models.AutoField(primary_key=True, serialize=False)),
                ('nametiporecurso', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tiporecurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.usuario')),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.usuario')),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.usuario')),
                ('tareascompletadas', models.IntegerField(blank=True, null=True)),
                ('tiempototalempleado', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'desarrollador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jefeproyecto',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.usuario')),
                ('proyectosgestionados', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jefeproyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.usuario')),
            ],
            options={
                'db_table': 'tester',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuariorolmodulo',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.usuario')),
            ],
            options={
                'db_table': 'usuariorolmodulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monitoreotarea',
            fields=[
                ('idtarea', models.OneToOneField(db_column='idtarea', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.tarea')),
                ('fechainicioreal', models.DateField(blank=True, null=True)),
                ('fechafinreal', models.DateField(blank=True, null=True)),
                ('porcentajecompletado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alertagenerada', models.BooleanField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monitoreotarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultadosrnn',
            fields=[
                ('idtarea', models.OneToOneField(db_column='idtarea', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.tarea')),
                ('idmodelo', models.IntegerField()),
                ('duracionestimada', models.IntegerField(blank=True, null=True)),
                ('costoestimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('recursos', models.TextField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultadosrnn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarearecurso',
            fields=[
                ('idtarea', models.OneToOneField(db_column='idtarea', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.tarea')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarearecurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recursohumano',
            fields=[
                ('idrecurso', models.OneToOneField(db_column='idrecurso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.recurso')),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('tarifahora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'recursohumano',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recursomaterial',
            fields=[
                ('idrecurso', models.OneToOneField(db_column='idrecurso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.recurso')),
                ('costounidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechacompra', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recursomaterial',
                'managed': False,
            },
        ),
    ]
