# Generated by Django 5.1.4 on 2025-01-03 08:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("idusuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombreusuario", models.CharField(max_length=255, unique=True)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("contrasena", models.CharField(max_length=255)),
                ("rol", models.CharField(max_length=50)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("confirmado", models.BooleanField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
                "managed": True,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                ("idalerta", models.AutoField(primary_key=True, serialize=False)),
                ("tipoalerta", models.CharField(blank=True, max_length=50, null=True)),
                ("mensaje", models.TextField()),
                ("activa", models.BooleanField(blank=True, null=True)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "alerta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                ("idequipo", models.AutoField(primary_key=True, serialize=False)),
                ("nombreequipo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "equipo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Modeloestimacionrnn",
            fields=[
                ("idmodelo", models.AutoField(primary_key=True, serialize=False)),
                ("nombremodelo", models.CharField(max_length=255)),
                ("descripcionmodelo", models.TextField(blank=True, null=True)),
                (
                    "versionmodelo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "modeloestimacionrnn",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                ("idtarea", models.AutoField(primary_key=True, serialize=False)),
                ("nombretarea", models.CharField(max_length=255)),
                ("fechainicio", models.DateField(blank=True, null=True)),
                ("fechafin", models.DateField(blank=True, null=True)),
                ("duracionestimada", models.IntegerField(blank=True, null=True)),
                ("duracionactual", models.IntegerField(blank=True, null=True)),
                ("dificultad", models.IntegerField(blank=True, null=True)),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("prioridad", models.IntegerField(blank=True, null=True)),
                (
                    "costoestimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "costoactual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tarea",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                ("idrecurso", models.AutoField(primary_key=True, serialize=False)),
                ("nombrerecurso", models.CharField(max_length=255)),
                ("disponibilidad", models.BooleanField(blank=True, null=True)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "recurso",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Requerimiento",
            fields=[
                (
                    "idrequerimiento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.TextField()),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "requerimiento",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Rolmoduloacceso",
            fields=[
                ("idrolmodulo", models.AutoField(primary_key=True, serialize=False)),
                ("nombrerol", models.CharField(max_length=50)),
                ("modulo", models.CharField(max_length=255)),
                ("permisos", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "rolmoduloacceso",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tiporecurso",
            fields=[
                ("idtiporecurso", models.AutoField(primary_key=True, serialize=False)),
                ("nametiporecurso", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "tiporecurso",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "idusuario",
                    models.OneToOneField(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "administrador",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "idusuario",
                    models.OneToOneField(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cliente",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Desarrollador",
            fields=[
                (
                    "idusuario",
                    models.OneToOneField(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tareascompletadas", models.IntegerField(blank=True, null=True)),
                ("tiempototalempleado", models.DurationField(blank=True, null=True)),
            ],
            options={
                "db_table": "desarrollador",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Jefeproyecto",
            fields=[
                (
                    "idusuario",
                    models.OneToOneField(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("proyectosgestionados", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "jefeproyecto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tester",
            fields=[
                (
                    "idusuario",
                    models.OneToOneField(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tester",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                ("idactividad", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("accion", models.CharField(max_length=255)),
                (
                    "idusuario",
                    models.ForeignKey(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "actividad",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Historialalerta",
            fields=[
                ("idhistorial", models.AutoField(primary_key=True, serialize=False)),
                ("fecharesolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "idalerta",
                    models.ForeignKey(
                        db_column="idalerta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.alerta",
                    ),
                ),
            ],
            options={
                "db_table": "historialalerta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Entradamodeloestimacionrnn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funcionentrada", models.TextField(blank=True, null=True)),
                ("tipodato", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "idmodelo",
                    models.ForeignKey(
                        db_column="idmodelo",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.modeloestimacionrnn",
                    ),
                ),
            ],
            options={
                "db_table": "entradamodeloestimacionrnn",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Monitoreotarea",
            fields=[
                (
                    "idtarea",
                    models.OneToOneField(
                        db_column="idtarea",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.tarea",
                    ),
                ),
                ("fechainicioreal", models.DateField(blank=True, null=True)),
                ("fechafinreal", models.DateField(blank=True, null=True)),
                (
                    "porcentajecompletado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("alertagenerada", models.BooleanField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "monitoreotarea",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Historialtarea",
            fields=[
                (
                    "idhistorialtarea",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fechacambio", models.DateTimeField(blank=True, null=True)),
                ("descripcioncambio", models.TextField()),
                (
                    "idtarea",
                    models.ForeignKey(
                        db_column="idtarea",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.tarea",
                    ),
                ),
            ],
            options={
                "db_table": "historialtarea",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="alerta",
            name="idtarea",
            field=models.ForeignKey(
                db_column="idtarea",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.tarea",
            ),
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                ("idnotificacion", models.AutoField(primary_key=True, serialize=False)),
                ("mensaje", models.TextField()),
                ("leido", models.BooleanField(blank=True, null=True)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Frontend", "Frontend"),
                            ("Backend", "Backend"),
                            ("QA", "QA"),
                            ("Otro", "Otro"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                ("archivada", models.BooleanField(default=False)),
                ("fecha_recordatorio", models.DateTimeField(blank=True, null=True)),
                (
                    "idusuario",
                    models.ForeignKey(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notificacion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Historialnotificacion",
            fields=[
                ("idhistorial", models.AutoField(primary_key=True, serialize=False)),
                ("fechalectura", models.DateTimeField(blank=True, null=True)),
                (
                    "idnotificacion",
                    models.ForeignKey(
                        db_column="idnotificacion",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.notificacion",
                    ),
                ),
            ],
            options={
                "db_table": "historialnotificacion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                ("idproyecto", models.AutoField(primary_key=True, serialize=False)),
                ("nombreproyecto", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fechainicio", models.DateField(blank=True, null=True)),
                ("fechafin", models.DateField(blank=True, null=True)),
                (
                    "presupuesto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "presupuestoutilizado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=50, null=True)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
                (
                    "idequipo",
                    models.ForeignKey(
                        blank=True,
                        db_column="idequipo",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.equipo",
                    ),
                ),
            ],
            options={
                "db_table": "proyecto",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Recursomaterial",
            fields=[
                (
                    "idrecurso",
                    models.OneToOneField(
                        db_column="idrecurso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.recurso",
                    ),
                ),
                (
                    "costounidad",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fechacompra", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "recursomaterial",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Miembro",
            fields=[
                ("idmiembro", models.AutoField(primary_key=True, serialize=False)),
                (
                    "idequipo",
                    models.ForeignKey(
                        db_column="idequipo",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.equipo",
                    ),
                ),
                (
                    "idrecurso",
                    models.ForeignKey(
                        db_column="idrecurso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.recurso",
                    ),
                ),
            ],
            options={
                "db_table": "miembro",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                ("idreporte", models.AutoField(primary_key=True, serialize=False)),
                ("tiporeporte", models.CharField(max_length=50)),
                ("fechageneracion", models.DateTimeField(blank=True, null=True)),
                (
                    "idproyecto",
                    models.ForeignKey(
                        db_column="idproyecto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.proyecto",
                    ),
                ),
            ],
            options={
                "db_table": "reporte",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Historialreporte",
            fields=[
                (
                    "idhistorialreporte",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
                ("descripcioncambio", models.TextField()),
                (
                    "idreporte",
                    models.ForeignKey(
                        db_column="idreporte",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.reporte",
                    ),
                ),
            ],
            options={
                "db_table": "historialreporte",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Reporteusuario",
            fields=[
                (
                    "idreporteusuario",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                (
                    "idreporte",
                    models.ForeignKey(
                        db_column="idreporte",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.reporte",
                    ),
                ),
                (
                    "idusuario",
                    models.ForeignKey(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporteusuario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Historialreporteusuario",
            fields=[
                (
                    "idhistorialreporteusuario",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cambio", models.TextField()),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
                (
                    "idreporteusuario",
                    models.ForeignKey(
                        db_column="idreporteusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.reporteusuario",
                    ),
                ),
            ],
            options={
                "db_table": "historialreporteusuario",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="tarea",
            name="idrequerimiento",
            field=models.ForeignKey(
                db_column="idrequerimiento",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.requerimiento",
            ),
        ),
        migrations.AddField(
            model_name="requerimiento",
            name="idproyecto",
            field=models.ForeignKey(
                db_column="idproyecto",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.proyecto",
            ),
        ),
        migrations.CreateModel(
            name="Salidamodeloestimacionrnn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metricasalida", models.TextField(blank=True, null=True)),
                ("tipodato", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "idmodelo",
                    models.ForeignKey(
                        db_column="idmodelo",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.modeloestimacionrnn",
                    ),
                ),
            ],
            options={
                "db_table": "salidamodeloestimacionrnn",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="recurso",
            name="idtiporecurso",
            field=models.ForeignKey(
                db_column="idtiporecurso",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.tiporecurso",
            ),
        ),
        migrations.CreateModel(
            name="Resultadosrnn",
            fields=[
                (
                    "idtarea",
                    models.OneToOneField(
                        db_column="idtarea",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.tarea",
                    ),
                ),
                ("idmodelo", models.IntegerField()),
                ("duracionestimada", models.IntegerField(blank=True, null=True)),
                (
                    "costoestimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("recursos", models.TextField(blank=True, null=True)),
                ("fechacreacion", models.DateTimeField(blank=True, null=True)),
                ("fechamodificacion", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "resultadosrnn",
                "managed": True,
                "unique_together": {("idtarea", "idmodelo")},
            },
        ),
        migrations.CreateModel(
            name="Recursohumano",
            fields=[
                (
                    "idrecurso",
                    models.OneToOneField(
                        db_column="idrecurso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.recurso",
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=255, null=True)),
                ("habilidades", models.TextField(blank=True, null=True)),
                (
                    "tarifahora",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "idusuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="idusuario",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recursohumano",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Usuariorolmodulo",
            fields=[
                (
                    "idusuario",
                    models.OneToOneField(
                        db_column="idusuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idrolmodulo",
                    models.ForeignKey(
                        db_column="idrolmodulo",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.rolmoduloacceso",
                    ),
                ),
            ],
            options={
                "db_table": "usuariorolmodulo",
                "managed": True,
                "unique_together": {("idusuario", "idrolmodulo")},
            },
        ),
        migrations.CreateModel(
            name="Tarearecurso",
            fields=[
                (
                    "idtarea",
                    models.OneToOneField(
                        db_column="idtarea",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.tarea",
                    ),
                ),
                ("cantidad", models.IntegerField(blank=True, null=True)),
                (
                    "idrecurso",
                    models.ForeignKey(
                        db_column="idrecurso",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.recurso",
                    ),
                ),
            ],
            options={
                "db_table": "tarearecurso",
                "managed": True,
                "unique_together": {("idtarea", "idrecurso")},
            },
        ),
    ]
