# Generated by Django 5.1.4 on 2025-03-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('idfase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'fase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('idtipotarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tipotarea',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='carga_trabajo',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='claridad_requisitos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tamaño_estimado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarearecurso',
            name='experiencia',
            field=models.IntegerField(blank=True, choices=[(1, 'Novato'), (2, 'Principiante'), (3, 'Competente'), (4, 'Proficiente'), (5, 'Experto')], null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fase',
            field=models.ForeignKey(blank=True, db_column='idfase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fase'),
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('idhistorialequipo', models.AutoField(primary_key=True, serialize=False)),
                ('completitud_tareas', models.FloatField(blank=True, null=True)),
                ('tiempo_promedio_tareas', models.FloatField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('idequipo', models.ForeignKey(db_column='idequipo', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.equipo')),
            ],
            options={
                'db_table': 'historialequipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TareaComun',
            fields=[
                ('idtareacomun', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_promedio', models.FloatField(blank=True, null=True)),
                ('variabilidad_tiempo', models.FloatField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('idtipotarea', models.ForeignKey(blank=True, db_column='idtipotarea', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipotarea')),
            ],
            options={
                'db_table': 'tareacomun',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.ForeignKey(blank=True, db_column='idtipotarea', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipotarea'),
        ),
        migrations.CreateModel(
            name='TareaTareaComun',
            fields=[
                ('idrelacion', models.AutoField(primary_key=True, serialize=False)),
                ('similitud', models.FloatField(blank=True, default=1.0, null=True)),
                ('idtarea', models.ForeignKey(db_column='idtarea', on_delete=django.db.models.deletion.CASCADE, to='dashboard.tarea')),
                ('idtareacomun', models.ForeignKey(db_column='idtareacomun', on_delete=django.db.models.deletion.CASCADE, to='dashboard.tareacomun')),
            ],
            options={
                'db_table': 'tareatarea_comun',
                'managed': True,
                'unique_together': {('idtarea', 'idtareacomun')},
            },
        ),
    ]
