# Generated by Django 5.1.4 on 2025-01-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='idactividad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
