# Generated by Django 5.1.4 on 2025-03-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fase_tipotarea_recurso_carga_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosrnn',
            name='duracionestimada',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
