# Generated by Django 5.1.4 on 2024-12-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notificacion_archivada_notificacion_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('QA', 'QA'), ('Otro', 'Otro')], default='media', max_length=20),
        ),
    ]
