# Generated by Django 5.1.4 on 2025-01-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_actividad_idactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('testing', 'testing'), ('deployment', 'Deployment')], default='media', max_length=20),
        ),
    ]
