# Generated by Django 5.1.4 on 2025-03-10 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_resultadosrnn_duracionestimada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='entidad_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='entidad_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='es_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConfiguracionAuditoria',
            fields=[
                ('idconfiguracion', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('campo', models.CharField(blank=True, max_length=100, null=True)),
                ('auditar_crear', models.BooleanField(default=True)),
                ('auditar_modificar', models.BooleanField(default=True)),
                ('auditar_eliminar', models.BooleanField(default=True)),
                ('nivel_detalle', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'configuracion_auditoria',
                'managed': True,
                'unique_together': {('modelo', 'campo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleActividad',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('idactividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.actividad')),
            ],
            options={
                'db_table': 'detalle_actividad',
                'managed': True,
            },
        ),
    ]
