# Generated by Django 5.1.4 on 2025-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_actividad_entidad_id_actividad_entidad_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneralAuditoria',
            fields=[
                ('idconfiguracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración General de Auditoría',
                'verbose_name_plural': 'Configuraciones Generales de Auditoría',
                'db_table': 'configuracion_general_auditoria',
                'managed': True,
            },
        ),
    ]
