# Generated by Django 5.1.4 on 2025-03-14 21:21

import dashboard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_configuraciongeneralauditoria'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', dashboard.models.CustomUserManager()),
            ],
        ),
    ]
