# Generated by Django 5.1.4 on 2024-12-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolmoduloacceso',
            options={'ordering': ['id'], 'verbose_name': 'Rol Modulo Acceso', 'verbose_name_plural': 'Roles Modulos Acceso'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuariorolmodulo',
            options={'ordering': ['id'], 'verbose_name': 'Usuario Rol Modulo', 'verbose_name_plural': 'Usuarios Roles Modulos'},
        ),
        migrations.AlterModelTable(
            name='rolmoduloacceso',
            table='rol_modulo_acceso',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.AlterModelTable(
            name='usuariorolmodulo',
            table='usuario_rol_modulo',
        ),
    ]
