# Generated by Django 5.1.4 on 2024-12-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Integración Externa',
                'verbose_name_plural': 'Integraciones Externas',
                'db_table': 'integracion_externa',
                'ordering': ['id'],
            },
        ),
    ]
