# Generated by Django 5.1.4 on 2025-03-30 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionJira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_servidor', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_jira', models.CharField(max_length=100)),
                ('frecuencia_sync', models.CharField(choices=[('manual', 'Manual'), ('hourly', 'Cada hora'), ('daily', 'Diaria'), ('weekly', 'Semanal')], default='manual', max_length=20)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integración Jira',
                'verbose_name_plural': 'Integraciones Jira',
            },
        ),
        migrations.CreateModel(
            name='JiraProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_local_id', models.IntegerField()),
                ('jira_project_id', models.CharField(max_length=100)),
                ('jira_project_key', models.CharField(max_length=20)),
                ('integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracion.integracionjira')),
            ],
            options={
                'unique_together': {('integracion', 'proyecto_local_id')},
            },
        ),
        migrations.CreateModel(
            name='JiraTaskMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_local_id', models.IntegerField()),
                ('jira_issue_id', models.CharField(max_length=100)),
                ('jira_issue_key', models.CharField(max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracion.integracionjira')),
            ],
            options={
                'unique_together': {('integracion', 'tarea_local_id')},
            },
        ),
    ]
