# Generated by Django 5.1.4 on 2025-03-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integracionjira',
            options={'managed': True, 'verbose_name': 'Integración Jira', 'verbose_name_plural': 'Integraciones Jira'},
        ),
        migrations.AlterModelOptions(
            name='jiraprojectmapping',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='jirataskmapping',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='integracionjira',
            table='integracionjira',
        ),
        migrations.AlterModelTable(
            name='jiraprojectmapping',
            table='jiraprojectmapping',
        ),
        migrations.AlterModelTable(
            name='jirataskmapping',
            table='jirataskmapping',
        ),
    ]
