# Generated by Django 5.1.4 on 2025-03-30 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracion', '0002_alter_integracionjira_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionjira',
            name='exportar_tareas',
            field=models.BooleanField(default=True, help_text='Si está activo, exporta tareas locales a Jira'),
        ),
        migrations.AddField(
            model_name='integracionjira',
            name='importar_issues',
            field=models.BooleanField(default=True, help_text='Si está activo, importa issues desde Jira'),
        ),
        migrations.AddField(
            model_name='integracionjira',
            name='sincronizar_adjuntos',
            field=models.BooleanField(default=False, help_text='Si está activo, sincroniza archivos adjuntos'),
        ),
        migrations.AddField(
            model_name='integracionjira',
            name='sync_comentarios',
            field=models.BooleanField(default=True, help_text='Si está activo, sincroniza comentarios'),
        ),
        migrations.CreateModel(
            name='JiraComentarioMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_local_id', models.IntegerField(blank=True, null=True)),
                ('jira_comment_id', models.CharField(max_length=100)),
                ('jira_issue_key', models.CharField(max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracion.integracionjira')),
            ],
            options={
                'db_table': 'jiracomentariomapping',
                'managed': True,
                'unique_together': {('integracion', 'jira_comment_id')},
            },
        ),
        migrations.CreateModel(
            name='JiraUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_local_id', models.IntegerField()),
                ('jira_user_id', models.CharField(max_length=100)),
                ('jira_user_key', models.CharField(max_length=100)),
                ('jira_user_name', models.CharField(max_length=100)),
                ('integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integracion.integracionjira')),
            ],
            options={
                'db_table': 'jirausermapping',
                'managed': True,
                'unique_together': {('integracion', 'usuario_local_id')},
            },
        ),
    ]
