# Generated by Django 5.1.4 on 2024-12-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReporteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.TextField()),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoReporte', models.CharField(max_length=50)),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='gestion_proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('descripcionCambio', models.TextField()),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reporte.reporte')),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'db_table': 'historial_reporte',
            },
        ),
        migrations.CreateModel(
            name='ReporteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='reporte.reporte')),
            ],
            options={
                'verbose_name': 'Reporte Usuario',
                'verbose_name_plural': 'Reportes Usuarios',
                'db_table': 'reporte_usuario',
            },
        ),
    ]
