# Generated by Django 5.1.4 on 2024-12-23 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialreporteusuario',
            name='reporteUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reporte.reporteusuario'),
        ),
    ]
